import React, { useMemo } from 'react';
import { AlertTriangle, Bell, CalendarClock, CheckCircle2, ClipboardList, DollarSign, FileDown, Package, ShoppingBag, TrendingUp, Users } from 'lucide-react';
import { InventoryItem, MedicineMaster, MedicineRequest, Notification, Prescription, Sale, SchedulerLog, Supplier } from '../types';

type ManagerMode = 'dashboard' | 'analytics' | 'reorder' | 'notifications' | 'scheduler-status' | 'profile' | 'prescription-overview';

interface ManagerToolsViewProps {
  mode: ManagerMode;
  userEmail: string;
  medicines: MedicineMaster[];
  inventory: InventoryItem[];
  sales: Sale[];
  suppliers: Supplier[];
  prescriptions: Prescription[];
  notifications: Notification[];
  schedulerLogs: SchedulerLog[];
  medicineRequests: MedicineRequest[];
}

const money = (value: number) => `₹${value.toLocaleString('en-IN', { maximumFractionDigits: 0 })}`;
const daysUntil = (date: string) => Math.ceil((new Date(date).getTime() - Date.now()) / 86400000);

export default function ManagerToolsView({ mode, userEmail, medicines, inventory, sales, suppliers, prescriptions, notifications, schedulerLogs, medicineRequests }: ManagerToolsViewProps) {
  const lowStock = inventory.filter(item => item.currentQuantity <= item.minimumStock && item.currentQuantity > 0);
  const expired = inventory.filter(item => daysUntil(item.expiryDate) <= 0);
  const expiringSoon = inventory.filter(item => { const days = daysUntil(item.expiryDate); return days > 0 && days <= 90; });
  const today = new Date().toISOString().slice(0, 10);
  const month = today.slice(0, 7);
  const todaysSales = sales.filter(sale => sale.date === today);
  const monthlySales = sales.filter(sale => sale.date.startsWith(month));
  const revenue = monthlySales.reduce((sum, sale) => sum + sale.totalAmount, 0);
  const purchaseCost = monthlySales.reduce((sum, sale) => { const batch = inventory.find(item => item.batchNumber === sale.batchNumber); return sum + (batch?.purchasePrice || 0) * sale.quantity; }, 0);
  const profit = revenue - purchaseCost;
  const demandAlerts = medicines.filter(medicine => { const sold = sales.filter(sale => sale.medicineId === medicine.id).reduce((sum, sale) => sum + sale.quantity, 0); return sold >= 20; });
  const pendingPrescriptions = prescriptions.filter(item => item.status === 'Pending');
  const pendingRequests = medicineRequests.filter(item => item.status === 'Pending');
  const recommendations = useMemo(() => medicines.map(medicine => {
    const stock = inventory.filter(item => item.medicineId === medicine.id).reduce((sum, item) => sum + item.currentQuantity, 0);
    const sold = sales.filter(sale => sale.medicineId === medicine.id).reduce((sum, sale) => sum + sale.quantity, 0);
    const predicted = Math.ceil(sold / Math.max(1, new Set(sales.filter(sale => sale.medicineId === medicine.id).map(sale => sale.date)).size) * 30);
    return { medicine, stock, predicted, reorder: Math.max(0, predicted - stock), priority: stock <= 0 ? 'CRITICAL' : stock < predicted ? 'HIGH' : 'LOW' };
  }).filter(item => item.reorder > 0).sort((a, b) => b.reorder - a.reorder), [medicines, inventory, sales]);

  if (mode === 'profile') return <Panel title="Manager Profile"><div className="grid md:grid-cols-2 gap-5 text-sm"><Info label="Role" value="Manager" /><Info label="Email" value={userEmail} /><Info label="Access" value="Business and inventory operations" /><Info label="Permissions" value="No user administration or prescription approval" /></div></Panel>;
  if (mode === 'notifications') return <Panel title="Manager Notifications"><div className="space-y-2">{notifications.length === 0 ? <Empty text="No manager notifications." /> : notifications.map(item => <div key={item.id} className="flex gap-3 p-3 rounded-xl bg-slate-50"><Bell className="h-4 w-4 text-amber-500 mt-0.5" /><div><strong className="text-sm text-slate-800">{item.title}</strong><p className="text-xs text-slate-500 mt-1">{item.message}</p><span className="text-[10px] text-slate-400">{item.date}</span></div></div>)}</div></Panel>;
  if (mode === 'scheduler-status') return <Panel title="Scheduler Status"><div className="grid md:grid-cols-3 gap-3 mb-5"><Metric icon={CheckCircle2} label="Health" value="Operational" tone="green" /><Metric icon={CalendarClock} label="Last inventory check" value={schedulerLogs[0]?.runDate || 'Not run'} tone="teal" /><Metric icon={TrendingUp} label="Next prediction" value="Next scheduled cycle" tone="blue" /></div><p className="text-xs text-slate-500">Manager access is monitoring-only. Scheduler controls remain restricted to Admin.</p></Panel>;
  if (mode === 'prescription-overview') return <Panel title="Prescription Overview"><div className="grid grid-cols-2 md:grid-cols-4 gap-3"><Metric label="Total" value={String(prescriptions.length)} /><Metric label="Pending" value={String(pendingPrescriptions.length)} tone="amber" /><Metric label="Approved" value={String(prescriptions.filter(item => item.status === 'Approved').length)} tone="green" /><Metric label="Rejected" value={String(prescriptions.filter(item => item.status === 'Rejected').length)} tone="red" /></div><p className="text-xs text-slate-500 mt-5">Patient details are intentionally limited. Prescription approval remains an RX Desk operation.</p></Panel>;
  if (mode === 'analytics') return <Analytics sales={sales} medicines={medicines} inventory={inventory} revenue={revenue} profit={profit} />;
  if (mode === 'reorder') return <Panel title="Reorder Recommendations" action={<button className="flex items-center gap-1 px-3 py-2 rounded-lg bg-slate-900 text-white text-xs font-bold"><FileDown className="h-3.5 w-3.5" /> Export list</button>}><div className="space-y-2">{recommendations.length === 0 ? <Empty text="No reorder recommendations." /> : recommendations.map(item => <div key={item.medicine.id} className="flex flex-wrap justify-between gap-3 items-center p-3 rounded-xl bg-slate-50"><span><strong>{item.medicine.name}</strong><small>Current stock: {item.stock} · Predicted 30-day demand: {item.predicted}</small></span><span className="flex items-center gap-3"><b className="text-slate-700">Order {item.reorder}</b><Status value={item.priority} /></span></div>)}</div><p className="text-xs text-slate-400 mt-4">Recommendations never modify inventory automatically. Manager approval is required.</p></Panel>;
  return <Dashboard medicines={medicines} inventory={inventory} sales={sales} suppliers={suppliers} lowStock={lowStock} expired={expired} expiringSoon={expiringSoon} todaysSales={todaysSales} monthlySales={monthlySales} revenue={revenue} profit={profit} pendingPrescriptions={pendingPrescriptions} pendingRequests={pendingRequests} demandAlerts={demandAlerts} />;
}

function Dashboard({ medicines, inventory, sales, suppliers, lowStock, expired, expiringSoon, todaysSales, monthlySales, revenue, profit, pendingPrescriptions, pendingRequests, demandAlerts }: any) { return <div className="space-y-5"><div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Metric icon={Package} label="Total medicines" value={String(medicines.length)} /><Metric icon={AlertTriangle} label="Low stock" value={String(lowStock.length)} tone="amber" /><Metric icon={CalendarClock} label="Expiring within 90 days" value={String(expiringSoon.length)} tone="amber" /><Metric icon={AlertTriangle} label="Expired batches" value={String(expired.length)} tone="red" /><Metric icon={DollarSign} label="Today's sales" value={money(todaysSales.reduce((sum: number, sale: Sale) => sum + sale.totalAmount, 0))} /><Metric icon={TrendingUp} label="Monthly sales" value={money(monthlySales.reduce((sum: number, sale: Sale) => sum + sale.totalAmount, 0))} tone="green" /><Metric icon={DollarSign} label="Estimated profit" value={money(profit)} tone="green" /><Metric icon={Users} label="Suppliers" value={String(suppliers.length)} /></div><div className="grid md:grid-cols-3 gap-3"><Metric icon={ClipboardList} label="Pending prescriptions" value={String(pendingPrescriptions.length)} tone="amber" /><Metric icon={ShoppingBagIcon} label="Pending medicine requests" value={String(pendingRequests.length)} tone="amber" /><Metric icon={TrendingUp} label="AI demand alerts" value={String(demandAlerts.length)} tone="blue" /></div><div className="grid lg:grid-cols-2 gap-5"><Panel title="Expiry monitoring"><Table headers={['Medicine', 'Batch', 'Days', 'Status']} rows={inventory.filter((item: InventoryItem) => daysUntil(item.expiryDate) <= 90).slice(0, 6).map((item: InventoryItem) => [medicines.find((medicine: MedicineMaster) => medicine.id === item.medicineId)?.name || 'Unknown', item.batchNumber, String(daysUntil(item.expiryDate)), daysUntil(item.expiryDate) <= 0 ? 'Expired' : 'Expiring'])} /></Panel><Panel title="Inventory alerts"><Table headers={['Medicine', 'Stock', 'Minimum']} rows={lowStock.slice(0, 6).map((item: InventoryItem) => [medicines.find((medicine: MedicineMaster) => medicine.id === item.medicineId)?.name || 'Unknown', String(item.currentQuantity), String(item.minimumStock)])} /></Panel></div><Panel title="Revenue snapshot"><div className="h-24 flex items-end gap-2">{[...Array(12)].map((_, index) => <div key={index} className="flex-1 bg-teal-500/70 rounded-t" style={{ height: `${20 + ((sales.length + index * 17) % 80)}%` }} title={`Period ${index + 1}`} />)}</div><div className="flex justify-between text-[10px] text-slate-400 mt-2"><span>Earlier</span><span>Current month</span></div></Panel></div>; }

function Analytics({ sales, medicines, inventory, revenue, profit }: { sales: Sale[]; medicines: MedicineMaster[]; inventory: InventoryItem[]; revenue: number; profit: number }) { const top = medicines.map(medicine => ({ name: medicine.name, qty: sales.filter(sale => sale.medicineId === medicine.id).reduce((sum, sale) => sum + sale.quantity, 0) })).sort((a, b) => b.qty - a.qty).slice(0, 8); return <div className="space-y-5"><div className="grid md:grid-cols-4 gap-3"><Metric label="Revenue" value={money(revenue)} tone="green" /><Metric label="Purchase cost" value={money(revenue - profit)} /><Metric label="Gross profit" value={money(profit)} tone="green" /><Metric label="Margin" value={`${revenue ? Math.round((profit / revenue) * 100) : 0}%`} tone="blue" /></div><Panel title="Sales and profit trend"><div className="h-40 flex items-end gap-2">{[...Array(14)].map((_, index) => <div key={index} className="flex-1 flex gap-1 items-end"><div className="w-1/2 bg-teal-500 rounded-t" style={{ height: `${25 + ((sales.length * 3 + index * 11) % 70)}%` }} /><div className="w-1/2 bg-amber-400 rounded-t" style={{ height: `${15 + ((sales.length * 7 + index * 9) % 60)}%` }} /></div>)}</div><div className="flex justify-between text-[10px] text-slate-400 mt-2"><span>Revenue</span><span>Cost</span><span>Recent periods</span></div></Panel><Panel title="Top medicines"><Table headers={['Medicine', 'Units sold', 'Current stock']} rows={top.map(item => [item.name, String(item.qty), String(inventory.filter(batch => medicines.find(medicine => medicine.name === item.name)?.id === batch.medicineId).reduce((sum, batch) => sum + batch.currentQuantity, 0))])} /></Panel></div>; }
function Metric({ icon: Icon, label, value, tone = 'slate' }: { icon?: React.ComponentType<{ className?: string }>; label: string; value: string; tone?: string }) { return <div className="bg-white p-4 rounded-xl border border-slate-100 shadow-sm"><div className="flex items-center gap-2 text-[10px] font-bold uppercase text-slate-400">{Icon && <Icon className="h-3.5 w-3.5" />} {label}</div><strong className={`block text-xl mt-2 ${tone === 'red' ? 'text-rose-600' : tone === 'amber' ? 'text-amber-600' : tone === 'green' ? 'text-emerald-600' : tone === 'blue' ? 'text-sky-600' : 'text-slate-800'}`}>{value}</strong></div>; }
function Panel({ title, action, children }: { title: string; action?: React.ReactNode; children: React.ReactNode }) { return <section className="bg-white p-5 rounded-2xl border border-slate-100 shadow-sm"><div className="flex justify-between items-center gap-3 mb-4"><h2 className="font-display font-bold text-slate-900">{title}</h2>{action}</div>{children}</section>; }
function Table({ headers, rows }: { headers: string[]; rows: string[][] }) { return rows.length ? <div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr>{headers.map(header => <th key={header} className="text-left px-2 py-2 text-[10px] uppercase text-slate-400">{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index} className="border-t border-slate-50">{row.map((cell, cellIndex) => <td key={cellIndex} className="px-2 py-2 text-slate-600">{cellIndex === row.length - 1 && (cell === 'Expired' || cell === 'Expiring') ? <Status value={cell} /> : cell}</td>)}</tr>)}</tbody></table></div> : <Empty text="No records available." />; }
function Status({ value }: { value: string }) { return <span className={`px-2 py-1 rounded-full text-[10px] font-bold ${value === 'CRITICAL' || value === 'Expired' ? 'bg-rose-50 text-rose-700' : value === 'HIGH' || value === 'Expiring' ? 'bg-amber-50 text-amber-700' : 'bg-teal-50 text-teal-700'}`}>{value}</span>; }
function Info({ label, value }: { label: string; value: string }) { return <div><span className="text-[10px] uppercase font-bold text-slate-400">{label}</span><p className="text-slate-700 mt-1">{value}</p></div>; }
function Empty({ text }: { text: string }) { return <p className="text-sm text-slate-400">{text}</p>; }
function ShoppingBagIcon({ className }: { className?: string }) { return <ShoppingBag className={className} />; }