import React, { useMemo, useState } from 'react';
import { Bell, FileText, HeartPulse, LifeBuoy, MapPin, Plus, Receipt, Search, ShoppingBag, Star, User, X } from 'lucide-react';
import { Customer, MedicineMaster, MedicineReminder, MedicineRequest, Notification, PatientFeedback, Prescription, RefillRequest, Sale, SupportTicket } from '../types';
import { UserAccount } from '../services/api';
import ProfileView from './ProfileView';

interface PatientPortalViewProps {
  email: string; customers: Customer[]; sales: Sale[]; medicines: MedicineMaster[]; prescriptions: Prescription[]; notifications: Notification[];
  onSubmitPrescription: (prescription: Omit<Prescription, 'id' | 'status'>, patientEmail: string, customerId?: string) => void;
  medicineRequests: MedicineRequest[]; refillRequests: RefillRequest[]; reminders: MedicineReminder[]; supportTickets: SupportTicket[];
  onAddMedicineRequest: (request: Omit<MedicineRequest, 'id' | 'createdAt' | 'status'>) => void;
  onAddRefillRequest: (request: Omit<RefillRequest, 'id' | 'createdAt' | 'status'>) => void;
  onAddReminder: (reminder: Omit<MedicineReminder, 'id'>) => void; onUpdateReminder: (id: string, enabled: boolean) => void;
  onAddSupportTicket: (ticket: Omit<SupportTicket, 'id' | 'createdAt' | 'status'>) => void; onAddFeedback: (feedback: Omit<PatientFeedback, 'id' | 'createdAt'>) => void;
  profileUser: UserAccount;
  onSaveProfile: (details: Partial<UserAccount>) => void;
}
type PortalTab = 'dashboard' | 'medicines' | 'prescriptions' | 'requests' | 'reminders' | 'orders' | 'support' | 'profile';
const statusColors: Record<string, string> = { Pending: 'bg-amber-50 text-amber-700', Verified: 'bg-sky-50 text-sky-700', Preparing: 'bg-indigo-50 text-indigo-700', 'Ready for Pickup': 'bg-teal-50 text-teal-700', Completed: 'bg-emerald-50 text-emerald-700', Rejected: 'bg-rose-50 text-rose-700', Approved: 'bg-emerald-50 text-emerald-700', Dispensed: 'bg-emerald-50 text-emerald-700' };

export default function PatientPortalView(props: PatientPortalViewProps) {
  const { email, customers, sales, medicines, prescriptions, notifications, medicineRequests, refillRequests, reminders, supportTickets } = props;
  const [tab, setTab] = useState<PortalTab>('dashboard'); const [search, setSearch] = useState('');
  const [showPrescription, setShowPrescription] = useState(false); const [showRequest, setShowRequest] = useState(false); const [showRefill, setShowRefill] = useState(false);
  const customer = useMemo(() => customers.find(item => item.email?.toLowerCase() === email.toLowerCase()), [customers, email]);
  const patientSales = useMemo(() => sales.filter(sale => sale.customerId === customer?.id || sale.customerName === customer?.name), [sales, customer]);
  const patientPrescriptions = useMemo(() => prescriptions.filter(item => item.patientEmail?.toLowerCase() === email.toLowerCase() || item.patientName === customer?.name), [prescriptions, email, customer]);
  const patientRequests = medicineRequests.filter(item => item.patientEmail.toLowerCase() === email.toLowerCase()); const patientRefills = refillRequests.filter(item => item.patientEmail.toLowerCase() === email.toLowerCase());
  const patientReminders = reminders.filter(item => item.patientEmail.toLowerCase() === email.toLowerCase()); const patientTickets = supportTickets.filter(item => item.patientEmail.toLowerCase() === email.toLowerCase());
  const medicineIds = new Set(patientSales.map(sale => sale.medicineId)); const myMedicines = medicines.filter(medicine => medicineIds.has(medicine.id));
  const patientNotifications = notifications.filter(item => item.patientEmail?.toLowerCase() === email.toLowerCase() || item.customerId === customer?.id || item.medicineIds?.some(id => medicineIds.has(id)));
  const filteredMedicines = medicines.filter(item => `${item.name} ${item.genericName} ${item.brand}`.toLowerCase().includes(search.toLowerCase()));
  const nav: Array<[PortalTab, string, React.ComponentType<{ className?: string }>]> = [['dashboard', 'Dashboard', HeartPulse], ['medicines', 'Medicine Search', Search], ['prescriptions', 'Prescriptions', FileText], ['requests', 'Requests & Refills', ShoppingBag], ['reminders', 'Reminders', Bell], ['orders', 'Bills & History', Receipt], ['support', 'Support & Feedback', LifeBuoy], ['profile', 'My Profile', User]];

  const submitPrescription = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const file = form.get('file'); const fileName = file instanceof File ? file.name : ''; const lines = String(form.get('medicines') || '').split('\n').filter(Boolean); props.onSubmitPrescription({ patientName: customer?.name || email, patientContact: customer?.contactNumber || '', doctorName: String(form.get('doctor') || ''), date: new Date().toISOString().split('T')[0], imageUrl: fileName || undefined, medicines: lines.map(line => { const [name, strength = '', qty = '1'] = line.split('|').map(value => value.trim()); return { name, strength, qty: Number(qty) || 1 }; }) }, email, customer?.id); setShowPrescription(false); };

  return <div className="space-y-5">
    <header className="bg-slate-950 text-white p-6 rounded-2xl border border-slate-800 shadow-lg"><span className="text-[10px] font-mono font-bold uppercase tracking-widest text-teal-400">Private patient portal</span><h1 className="font-display text-2xl font-bold mt-2">Welcome, {customer?.name || 'Patient'}</h1><p className="text-sm text-slate-400 mt-1">Your prescriptions, medicines, requests, reminders, and pharmacy care.</p></header>
    <nav className="flex gap-2 overflow-x-auto pb-1">{nav.map(([id, label, Icon]) => <button key={id} onClick={() => setTab(id)} className={`shrink-0 flex items-center gap-2 px-3 py-2 rounded-lg text-xs font-bold border ${tab === id ? 'bg-teal-600 text-white border-teal-600' : 'bg-white text-slate-500 border-slate-200 hover:border-teal-300'}`}><Icon className="h-3.5 w-3.5" />{label}</button>)}</nav>
    {tab === 'dashboard' && <div className="space-y-5"><div className="grid grid-cols-2 lg:grid-cols-5 gap-3">{[['Medicines', myMedicines.length], ['Prescriptions', patientPrescriptions.length], ['Requests', patientRequests.length + patientRefills.length], ['Reminders', patientReminders.filter(item => item.enabled).length], ['Purchases', patientSales.length]].map(([label, count]) => <div key={String(label)} className="bg-white p-4 rounded-xl border border-slate-100 shadow-sm"><span className="text-[10px] uppercase font-bold text-slate-400">{label}</span><strong className="block text-2xl text-slate-900 mt-1">{count}</strong></div>)}</div><div className="grid lg:grid-cols-2 gap-5"><Panel title="Active prescriptions"><Rows items={patientPrescriptions.filter(item => item.status !== 'Dispensed' && item.status !== 'Completed').slice(0, 4)} empty="No active prescriptions." render={item => <><span>{item.doctorName}<small>{item.date}</small></span><Status value={item.status} /></>} /></Panel><Panel title="Upcoming reminders"><Rows items={patientReminders.filter(item => item.enabled).slice(0, 4)} empty="No upcoming reminders." render={item => <><span>{medicines.find(med => med.id === item.medicineId)?.name || 'Medicine'}<small>{item.time} · {item.dosage}</small></span><Status value="Enabled" /></>} /></Panel></div><Panel title="Important notifications"><Rows items={patientNotifications.slice(0, 5)} empty="No patient notifications." render={item => <span><strong>{item.title}</strong><small>{item.message}</small></span>} /></Panel></div>}
    {tab === 'medicines' && <Panel title="Medicine Search"><div className="relative mb-4"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search by medicine name, generic name, or brand" className="field pl-9" /></div><div className="grid md:grid-cols-2 gap-3">{filteredMedicines.map(item => <div key={item.id} className="p-4 bg-slate-50 rounded-xl border border-slate-100"><div className="flex justify-between gap-2"><strong className="text-slate-800">{item.name}</strong><span className="text-[10px] font-bold text-teal-700">{item.category}</span></div><p className="text-xs text-slate-500 mt-2">{item.description}</p><p className="text-xs text-slate-600 mt-2"><b>Uses:</b> {item.category} · <b>Strength:</b> {item.strength} · <b>Storage:</b> {item.storageCondition}</p><p className="text-xs mt-2 font-bold text-emerald-600">Available for pharmacy review</p><p className="text-[10px] text-slate-400 mt-1">Use only as directed by a qualified healthcare professional.</p></div>)}</div></Panel>}
    {tab === 'prescriptions' && <div className="space-y-5"><Panel title="My prescriptions" action={<button onClick={() => setShowPrescription(true)} className="primary"><Plus className="h-3.5 w-3.5" /> Upload prescription</button>}><Rows items={patientPrescriptions} empty="No prescriptions linked to this account." render={item => <><span><strong>{item.id}</strong> · {item.doctorName}<small>{item.date} · {item.medicines.map(medicine => medicine.name).join(', ')}</small></span><Status value={item.status} /></>} /></Panel><Panel title="Upload status"><p className="text-sm text-slate-500">Uploaded prescriptions remain <b>Pending</b> until RX Desk verifies them. They are never automatically approved.</p></Panel>{showPrescription && <Modal title="Upload prescription" close={() => setShowPrescription(false)}><form onSubmit={submitPrescription} className="space-y-3"><input name="doctor" required placeholder="Doctor information" className="field" /><textarea name="medicines" required rows={4} placeholder="Medicine | strength | quantity" className="field" /><input name="file" type="file" accept="image/*,.pdf" className="field" /><button className="primary">Submit for RX Desk verification</button></form></Modal>}</div>}
    {tab === 'requests' && <div className="space-y-5"><Panel title="Medicine requests" action={<button onClick={() => setShowRequest(true)} className="primary"><Plus className="h-3.5 w-3.5" /> Request medicine</button>}><Rows items={patientRequests} empty="No medicine requests." render={item => <><span>{medicines.find(medicine => medicine.id === item.medicineId)?.name || 'Medicine'}<small>Quantity: {item.quantity} · {item.createdAt}</small></span><Status value={item.status} /></>} /></Panel><Panel title="Refill requests" action={<button onClick={() => setShowRefill(true)} className="primary"><Plus className="h-3.5 w-3.5" /> Request refill</button>}><Rows items={patientRefills} empty="No refill requests." render={item => <><span>{medicines.find(medicine => medicine.id === item.medicineId)?.name || 'Medicine'}<small>Quantity: {item.quantity} · {item.createdAt}</small></span><Status value={item.status} /></>} /></Panel>{showRequest && <RequestModal title="Request medicine" medicines={medicines} email={email} submit={props.onAddMedicineRequest} close={() => setShowRequest(false)} />}{showRefill && <RequestModal title="Request refill" medicines={myMedicines} email={email} submit={props.onAddRefillRequest} close={() => setShowRefill(false)} />}</div>}
    {tab === 'reminders' && <ReminderPanel email={email} medicines={myMedicines} reminders={patientReminders} onAdd={props.onAddReminder} onUpdate={props.onUpdateReminder} />}
    {tab === 'orders' && <div className="space-y-5"><Panel title="My bills"><Rows items={patientSales} empty="No bills found." render={item => <><span>Bill {item.id}<small>{item.date} · {item.quantity} units · {item.paymentMethod}</small></span><strong>₹{item.totalAmount.toFixed(2)}</strong></>} /></Panel><Panel title="Purchase history"><Rows items={patientSales} empty="No purchase history found." render={item => <><span>{medicines.find(medicine => medicine.id === item.medicineId)?.name || 'Medicine'}<small>{item.date} · Quantity {item.quantity} · Bill {item.id}</small></span><strong>₹{item.totalAmount.toFixed(2)}</strong></>} /></Panel><Panel title="Order tracking"><div className="grid grid-cols-2 md:grid-cols-5 gap-2">{['Request Submitted', 'Prescription Verified', 'Medicine Prepared', 'Ready for Pickup', 'Completed'].map((step, index) => <div key={step} className={`p-3 rounded-lg text-center text-[10px] font-bold ${index === 0 ? 'bg-teal-600 text-white' : 'bg-slate-100 text-slate-400'}`}><span className="block text-lg">{index + 1}</span>{step}</div>)}</div></Panel></div>}
    {tab === 'support' && <SupportPanel email={email} tickets={patientTickets} onAdd={props.onAddSupportTicket} onFeedback={props.onAddFeedback} />}
    {tab === 'profile' && <ProfileView user={props.profileUser} onSave={props.onSaveProfile} />}
  </div>;
}
function Panel({ title, action, children }: { title: string; action?: React.ReactNode; children: React.ReactNode }) { return <section className="bg-white p-5 rounded-2xl border border-slate-100 shadow-sm"><div className="flex justify-between items-center gap-3 mb-4"><h2 className="font-display font-bold text-slate-900">{title}</h2>{action}</div>{children}</section>; }
function Rows({ items, empty, render }: { items: unknown[]; empty: string; render: (item: any) => React.ReactNode }) { return items.length ? <div className="space-y-2">{items.map((item, index) => <div key={index} className="flex items-center justify-between gap-3 p-3 bg-slate-50 rounded-xl text-sm text-slate-700">{render(item)}</div>)}</div> : <p className="text-sm text-slate-400">{empty}</p>; }
function Status({ value }: { value: string }) { return <span className={`shrink-0 px-2 py-1 rounded-full text-[10px] font-bold ${statusColors[value] || 'bg-slate-100 text-slate-600'}`}>{value}</span>; }
function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 bg-slate-950/60 flex items-center justify-center p-4"><div className="bg-white rounded-2xl p-5 w-full max-w-lg shadow-xl"><div className="flex justify-between items-center mb-4"><h3 className="font-bold text-slate-900">{title}</h3><button onClick={close}><X className="h-4 w-4" /></button></div>{children}</div></div>; }
function RequestModal({ title, medicines, email, submit, close }: { title: string; medicines: MedicineMaster[]; email: string; submit: (request: { patientEmail: string; medicineId: string; quantity: number }) => void; close: () => void }) { const [medicineId, setMedicineId] = useState(medicines[0]?.id || ''); const [quantity, setQuantity] = useState(1); return <Modal title={title} close={close}><form onSubmit={event => { event.preventDefault(); submit({ patientEmail: email, medicineId, quantity }); close(); }} className="space-y-3"><select value={medicineId} onChange={event => setMedicineId(event.target.value)} className="field">{medicines.map(medicine => <option key={medicine.id} value={medicine.id}>{medicine.name}</option>)}</select><input type="number" min="1" value={quantity} onChange={event => setQuantity(Number(event.target.value))} className="field" /><button className="primary">Submit request</button></form></Modal>; }
function ReminderPanel({ email, medicines, reminders, onAdd, onUpdate }: { email: string; medicines: MedicineMaster[]; reminders: MedicineReminder[]; onAdd: (reminder: Omit<MedicineReminder, 'id'>) => void; onUpdate: (id: string, enabled: boolean) => void }) { const [medicineId, setMedicineId] = useState(medicines[0]?.id || ''); const [dosage, setDosage] = useState(''); const [time, setTime] = useState('Morning'); return <Panel title="Medicine reminders"><form onSubmit={event => { event.preventDefault(); onAdd({ patientEmail: email, medicineId, dosage, time, startDate: new Date().toISOString().split('T')[0], endDate: '', enabled: true }); setDosage(''); }} className="grid md:grid-cols-4 gap-2 mb-4"><select value={medicineId} onChange={event => setMedicineId(event.target.value)} className="field">{medicines.map(medicine => <option key={medicine.id} value={medicine.id}>{medicine.name}</option>)}</select><input required value={dosage} onChange={event => setDosage(event.target.value)} placeholder="Dosage" className="field" /><select value={time} onChange={event => setTime(event.target.value)} className="field"><option>Morning</option><option>Afternoon</option><option>Night</option><option>Custom time</option></select><button className="primary"><Plus className="h-3.5 w-3.5" /> Add reminder</button></form><Rows items={reminders} empty="No reminders created." render={item => <><span>{medicines.find(medicine => medicine.id === item.medicineId)?.name || 'Medicine'}<small>{item.dosage} · {item.time}</small></span><button onClick={() => onUpdate(item.id, !item.enabled)} className="text-xs font-bold text-teal-700">{item.enabled ? 'Enabled' : 'Disabled'}</button></>} /></Panel>; }
function SupportPanel({ email, tickets, onAdd, onFeedback }: { email: string; tickets: SupportTicket[]; onAdd: (ticket: Omit<SupportTicket, 'id' | 'createdAt' | 'status'>) => void; onFeedback: (feedback: Omit<PatientFeedback, 'id' | 'createdAt'>) => void }) { const [subject, setSubject] = useState(''); const [message, setMessage] = useState(''); const [rating, setRating] = useState(5); return <div className="space-y-5"><Panel title="Contact pharmacy"><form onSubmit={event => { event.preventDefault(); onAdd({ patientEmail: email, subject, message }); setSubject(''); setMessage(''); }} className="space-y-3"><input required value={subject} onChange={event => setSubject(event.target.value)} placeholder="Subject" className="field" /><textarea required value={message} onChange={event => setMessage(event.target.value)} placeholder="Message" rows={3} className="field" /><button className="primary"><LifeBuoy className="h-3.5 w-3.5" /> Send support message</button></form><Rows items={tickets} empty="No support messages." render={item => <span><strong>{item.subject}</strong><small>{item.status} · {item.response || 'Awaiting pharmacy response'}</small></span>} /></Panel><Panel title="Feedback & rating"><form onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); onFeedback({ patientEmail: email, rating, comments: String(form.get('comments') || '') }); event.currentTarget.reset(); }} className="space-y-3"><div className="flex gap-1">{[1, 2, 3, 4, 5].map(value => <button type="button" key={value} onClick={() => setRating(value)} className={value <= rating ? 'text-amber-500' : 'text-slate-300'}><Star className="h-5 w-5 fill-current" /></button>)}</div><textarea name="comments" placeholder="Tell us about your experience" rows={3} className="field" /><button className="primary">Submit feedback</button></form></Panel><Panel title="Pharmacy information"><p className="text-sm text-slate-600 flex items-center gap-2"><MapPin className="h-4 w-4 text-teal-600" /> PharmaSense Pharmacy · Contact the pharmacy team for address and opening hours.</p></Panel></div>; }