import React, { useMemo, useState } from 'react';
import { AlertTriangle, Bell, ClipboardCheck, FileText, Package, Search, ShoppingCart, User, Users } from 'lucide-react';
import { Customer, InventoryItem, MedicineMaster, MedicineRequest, Notification, Prescription, RefillRequest, Sale } from '../types';

type RxMode = 'dashboard' | 'requests' | 'refills' | 'medicine-search' | 'notifications' | 'reports' | 'profile';
interface RxDeskViewProps {
  mode: RxMode;
  userEmail: string;
  customers: Customer[];
  medicines: MedicineMaster[];
  inventory: InventoryItem[];
  sales: Sale[];
  prescriptions: Prescription[];
  medicineRequests: MedicineRequest[];
  refillRequests: RefillRequest[];
  notifications: Notification[];
  onUpdateMedicineRequest: (id: string, status: MedicineRequest['status']) => void;
  onUpdateRefillRequest: (id: string, status: RefillRequest['status']) => void;
}

const today = () => new Date().toISOString().slice(0, 10);
const statusClass = (status: string) => status === 'Completed' || status === 'Approved' ? 'bg-emerald-50 text-emerald-700' : status === 'Rejected' ? 'bg-rose-50 text-rose-700' : 'bg-amber-50 text-amber-700';

export default function RxDeskView({ mode, userEmail, customers, medicines, inventory, sales, prescriptions, medicineRequests, refillRequests, notifications, onUpdateMedicineRequest, onUpdateRefillRequest }: RxDeskViewProps) {
  const todaysPrescriptions = prescriptions.filter(item => item.date === today());
  const pendingPrescriptions = prescriptions.filter(item => item.status === 'Pending');
  const approvedToday = prescriptions.filter(item => item.status === 'Approved' && item.date === today());
  const todaysRequests = medicineRequests.filter(item => item.createdAt === today());
  const pendingRefills = refillRequests.filter(item => item.status === 'Pending');
  const todaysBills = sales.filter(item => item.date === today());
  const lowStock = inventory.filter(item => item.currentQuantity <= item.minimumStock);
  const readyForPickup = [...medicineRequests, ...refillRequests].filter(item => item.status === 'Ready for Pickup');
  const expiredMedicineIds = new Set(inventory.filter(item => new Date(item.expiryDate) <= new Date()).map(item => item.medicineId));

  if (mode === 'dashboard') return <div className="space-y-5"><Header title="RX Desk Dashboard" subtitle="Prescription verification, dispensing, patient handling, and billing support." /><div className="grid grid-cols-2 lg:grid-cols-3 gap-3"><Metric label="Pending prescriptions" value={pendingPrescriptions.length} tone="amber" icon={FileText} /><Metric label="Approved today" value={approvedToday.length} tone="green" icon={ClipboardCheck} /><Metric label="Medicine requests" value={todaysRequests.length} icon={Package} /><Metric label="Refill requests" value={pendingRefills.length} tone="amber" icon={ClipboardCheck} /><Metric label="Ready for pickup" value={readyForPickup.length} tone="green" icon={ShoppingCart} /><Metric label="Today's bills" value={todaysBills.length} icon={ShoppingCart} /></div><div className="grid lg:grid-cols-2 gap-5"><Panel title="Recent prescription activity"><Rows items={todaysPrescriptions.slice(0, 6)} empty="No prescriptions today." render={item => <><span><strong>{item.patientName}</strong><small>{item.doctorName} · {item.date}</small></span><Status value={item.status} /></>} /></Panel><Panel title="Operational alerts"><Rows items={[...notifications.filter(item => !item.isRead), ...lowStock].slice(0, 6)} empty="No active alerts." render={item => 'title' in item ? <span><strong>{item.title}</strong><small>{item.message}</small></span> : <span><strong>Low stock alert</strong><small>{medicines.find(medicine => medicine.id === item.medicineId)?.name || 'Medicine'} · {item.currentQuantity} remaining</small></span>} /></Panel></div><Panel title="Desk activity"><div className="grid grid-cols-2 md:grid-cols-4 gap-3"><Metric label="Patients" value={customers.length} icon={Users} /><Metric label="Prescriptions" value={prescriptions.length} icon={FileText} /><Metric label="Expiring batches" value={expiredMedicineIds.size} tone="amber" icon={AlertTriangle} /><Metric label="Notifications" value={notifications.filter(item => !item.isRead).length} tone="amber" icon={Bell} /></div></Panel></div>;
  if (mode === 'requests') return <Queue title="Medicine Requests" requests={medicineRequests} medicines={medicines} onUpdate={onUpdateMedicineRequest} />;
  if (mode === 'refills') return <Queue title="Refill Requests" requests={refillRequests} medicines={medicines} onUpdate={onUpdateRefillRequest} />;
  if (mode === 'medicine-search') return <MedicineSearch medicines={medicines} inventory={inventory} />;
  if (mode === 'notifications') return <Panel title="RX Desk Notifications"><Rows items={notifications} empty="No notifications." render={item => <span><strong>{item.title}</strong><small>{item.message} · {item.date}</small></span>} /></Panel>;
  if (mode === 'reports') return <Panel title="RX Desk Reports"><div className="grid grid-cols-2 md:grid-cols-4 gap-3"><Metric label="Today's prescriptions" value={todaysPrescriptions.length} /><Metric label="Completed prescriptions" value={prescriptions.filter(item => item.status === 'Completed' || item.status === 'Dispensed').length} tone="green" /><Metric label="Today's requests" value={todaysRequests.length} /><Metric label="Today's dispensing bills" value={todaysBills.length} /></div><p className="text-xs text-slate-500 mt-5">Financial, supplier, AI forecasting, and scheduler administration remain outside RX Desk access.</p></Panel>;
  return <Panel title="RX Desk Profile"><div className="grid md:grid-cols-2 gap-5 text-sm"><Info label="Role" value="RX Desk" /><Info label="Email" value={userEmail} /><Info label="Access" value="Prescription, patient, dispensing, request, and billing operations" /><Info label="Restricted" value="Supplier, profit, forecasting, scheduler, and user administration" /></div></Panel>;
}

function Queue({ title, requests, medicines, onUpdate }: { title: string; requests: Array<MedicineRequest | RefillRequest>; medicines: MedicineMaster[]; onUpdate: (id: string, status: MedicineRequest['status']) => void }) { return <Panel title={title}><Rows items={requests} empty={`No ${title.toLowerCase()}.`} render={item => <><span><strong>{item.id}</strong><small>{medicines.find(medicine => medicine.id === item.medicineId)?.name || 'Unknown medicine'} · Patient: {item.patientEmail} · Qty {item.quantity}</small></span><span className="flex items-center gap-2"><Status value={item.status} /><select value={item.status} onChange={event => onUpdate(item.id, event.target.value as MedicineRequest['status'])} className="text-[10px] border border-slate-200 rounded px-1.5 py-1"><option>Pending</option><option>Verified</option><option>Preparing</option><option>Ready for Pickup</option><option>Completed</option><option>Rejected</option></select></span></>} /></Panel>; }
function MedicineSearch({ medicines, inventory }: { medicines: MedicineMaster[]; inventory: InventoryItem[] }) { const [query, setQuery] = useState(''); const matches = useMemo(() => medicines.filter(item => `${item.name} ${item.genericName} ${item.brand} ${item.barcode}`.toLowerCase().includes(query.toLowerCase())), [medicines, query]); return <Panel title="Medicine Search & Availability"><div className="relative mb-4"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Name, generic, brand, barcode, or batch" className="w-full pl-9 px-3 py-2 text-sm border border-slate-200 rounded-lg" /></div><div className="grid md:grid-cols-2 gap-3">{matches.map(medicine => { const batches = inventory.filter(item => item.medicineId === medicine.id); const available = batches.reduce((sum, item) => sum + (new Date(item.expiryDate) > new Date() ? item.currentQuantity : 0), 0); return <div key={medicine.id} className="p-4 bg-slate-50 rounded-xl border border-slate-100"><div className="flex justify-between"><strong>{medicine.name}</strong><Status value={available > 0 ? 'Available' : 'Out of Stock'} /></div><p className="text-xs text-slate-500 mt-1">{medicine.genericName} · {medicine.category} · Barcode {medicine.barcode}</p><p className="text-xs text-slate-600 mt-2">Stock: {available} · Price: ₹{medicine.mrp.toFixed(2)}</p>{batches.slice(0, 2).map(batch => <p key={batch.id} className={`text-[10px] mt-1 ${new Date(batch.expiryDate) <= new Date() ? 'text-rose-600 font-bold' : 'text-slate-400'}`}>Batch {batch.batchNumber} · Expiry {batch.expiryDate} · {new Date(batch.expiryDate) <= new Date() ? 'Do not dispense' : `${batch.currentQuantity} units`}</p>)}</div>; })}</div></Panel>; }
function Header({ title, subtitle }: { title: string; subtitle: string }) { return <header className="bg-slate-950 text-white p-6 rounded-2xl border border-slate-800 shadow-lg"><span className="text-[10px] font-mono font-bold uppercase tracking-widest text-teal-400">RX Desk</span><h1 className="font-display text-2xl font-bold mt-2">{title}</h1><p className="text-sm text-slate-400 mt-1">{subtitle}</p></header>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="bg-white p-5 rounded-2xl border border-slate-100 shadow-sm"><h2 className="font-display font-bold text-slate-900 mb-4">{title}</h2>{children}</section>; }
function Rows<T>({ items, empty, render }: { items: T[]; empty: string; render: (item: T) => React.ReactNode }) { return items.length ? <div className="space-y-2">{items.map((item, index) => <div key={index} className="flex items-center justify-between gap-3 p-3 bg-slate-50 rounded-xl text-sm text-slate-700">{render(item)}</div>)}</div> : <p className="text-sm text-slate-400">{empty}</p>; }
function Status({ value }: { value: string }) { return <span className={`px-2 py-1 rounded-full text-[10px] font-bold ${statusClass(value)}`}>{value}</span>; }
function Metric({ icon: Icon, label, value, tone = 'slate' }: { icon?: React.ComponentType<{ className?: string }>; label: string; value: number; tone?: string }) { return <div className="bg-white p-4 rounded-xl border border-slate-100 shadow-sm"><div className="flex items-center gap-2 text-[10px] uppercase font-bold text-slate-400">{Icon && <Icon className="h-3.5 w-3.5" />}{label}</div><strong className={`block text-2xl mt-2 ${tone === 'amber' ? 'text-amber-600' : tone === 'green' ? 'text-emerald-600' : 'text-slate-800'}`}>{value}</strong></div>; }
function Info({ label, value }: { label: string; value: string }) { return <div><span className="text-[10px] uppercase font-bold text-slate-400">{label}</span><p className="text-slate-700 mt-1">{value}</p></div>; }
